name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/MyApp.Api.sln
    - name: Build
      run: dotnet build  src/**/*.csproj --no-restore
    - name: Unit Test
      run: dotnet test  src/**/*UnitTest*.csproj --no-build --verbosity normal
    - name: Integration Test
      run: dotnet test  src/**/*IntegrationTest*.csproj --no-build --verbosity normal
